name: four dates printed

on: push
      
jobs:
    # First job
    first_print:
        runs-on: ubuntu-latest

        steps:
            - name: print current date on ubuntu
              run: echo "The current date is $(date)"

    # Second job
    second_print:
        runs-on: windows-latest
        needs: first_print

        steps:
            - name: print current date on windows
              run: echo "The current date is $((Get-Date).ToString())"

    # Third job
    third_print:
        runs-on: macos-latest
        needs: second_print

        steps:
            - name: print current date on macos
              run: echo "The current date is $(date)"

    # Fourth Job
    fourth_print:
        runs-on: debian
        need: third_print

        steps:
            - name: print current date on debian
              run: echo "The current date is $(date)"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
